<html>
	<head>
		<title>Medaliensammlung</title>
		<meta charset="utf-8">
		<link rel="STYLESHEET" href="/css/styles.css" type="text/css">
		<meta name="viewport" content="width=device-width, minimum-scale=1.0, maximum-scale=1.0" />
	</head>

<body>

		<section id="body" class="width">
			<aside id="sidebar" class="column-left">

			<header>
				<h1><a href="#">anatine</a></h1>

				<h2>Welcome to my website!</h2>
				
			</header>

			<nav id="mainnav">
  				<ul>
            <li><a href="http://medal.tld/manufacturer/showAll">Hersteller</a></li>
			<li><a href="http://medal.tld/serie/showAll">Serien</a></li>
			<li><a href="http://medal.tld/storage/showAll">Aufbewahrung</a></li>
                        	</ul>
			</nav>

			
			
			</aside>
			
			<section id="content" class="column-right">
                		
	    <article>
	
	