<?php 

    
?>

<h1>Neue Storagemöglickeit anlegen</h1>

<form action="addNewDone" id="storage" method="post">

	<p><label class="h2" form="storage">Daten des Storage</label></p>
	
	<table>
    	
    	<tr>
    		<td><label for="name">Name:</label></td>
    		<td><input type="text" name="name" maxlength=30"></td>
    	</tr>
    	<tr>
    		<td><label for="manufacturerID">Hersteller:</label></td>
    		<td><select name="manufacturerID" size="1">
    <?php 
    foreach ($this->vars["MANUFACTURER"] as $manufacturer)
    {
          
        ?>
           <option value="<?php echo $manufacturer->ID; ?>"><?php echo $manufacturer->Name ?></option>";
           
    <?php } ?>

    		</select>
    		</td>
    	</tr>
    	<tr>
    		<td><label for="maximalAmount">Höchster Wert:</label></td>
    		<td><input type="text" name="maximalAmount" maxlength=30"></td>
    	</tr>
    </table>
	
 	<p><button type="reset">Eingaben zurücksetzen</button> 
 	<button type="submit">Eingaben absenden</button></p>

</form>



