<?php


?>

<h1>Neuen Hersteller anlegen</h1>

<form action="addNewDone" id="manufacturer" method="post">

	<p><label class="h2" form="manufacturer">Daten des Herstellers</label></p>
	
	<table>
    	<tr>
    		<td><label for="name">Name:</label></td>
    		<td><input type="text" name="name" maxlength=30"></td>
    	</tr>
    	
    	<tr>
    		<td><label for="wikipedia">Wikipedia:</label></td>
    		<td><input type="text" name="wikipedia" maxlength=150"></td>
		</tr>
	</table>
	
	<p><button type="reset">Eingaben zurücksetzen</button> 
 	<button type="submit">Eingaben absenden</button></p>

</form>