<?php

$manufacturer = "";
$manufacturer = $this->vars["MANUFACTURER"];


?>

<h1>Medaleur bearbeiten</h1>

<form action="../editDone" id="manufacturer" method="post">

	<input type=hidden name="ID" value="<?php echo $manufacturer->ID; ?>">
	
	<p><label class="h2" form="manufacturer">Daten des Herstellers</label></p>
	
	<table>
    	
    	<tr>
    		<td><label for="name">Name:</label></td>
    		<td><input type="text" name="name" maxlength=30" value="<?php echo $manufacturer->Name; ?>"></td>
    	</tr>
    	
    	<tr>
    		<td><label for="wikipedia">Wikipedia:</label></td>
    		<td><input type="text" name="wikipedia" maxlength=150" value="<?php echo $manufacturer->Wikipedia; ?>"></td>
		</tr>
	</table>
	
	
 	<p><button type="reset">Eingaben zurücksetzen</button> 
 	<button type="submit">Eingaben absenden</button></p>

</form>